/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Casacade Models (https://sketchfab.com/CasacadeOperations)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hennessy-venom-f5-22d6e6f9551146e0928e14275f8b9354
title: Hennessy Venom F5
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Hennesey Venom F5.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={100}>
            <group
              position={[0, -44.9, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
              scale={0.03}
            >
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group
                  position={[0, -3622.15, 1783.36]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_05_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -1647.63, -6006.18]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_06_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -2974.53, 7693.62]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_08_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[0, -3396.3, 6896.11]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_08_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[0, -3196.79, 6362.94]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_07_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[0, -3297.94, 6332.47]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_07_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[3722.73, -2293.32, 5974.61]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_25_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3582.82, -1360.72, 5974.24]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_14_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[-3652.64, -1340.5, 5974.17]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_13_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[-3654.55, -1340.5, 5974.17]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_08_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3224.54, -1348.44, 5974.16]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.tire_mat5_02_tire_mat5_0_tire_mat5_0_1.geometry
                    }
                    material={materials.tire_mat5}
                  />
                </group>
                <group
                  position={[-3224.54, -1348.44, 5974.16]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.tire_mat5_01_tire_mat5_0_tire_mat5_0_1.geometry
                    }
                    material={materials.tire_mat5}
                  />
                </group>
                <group
                  position={[0, -1947.35, 8197.17]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_03_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[0, -1655.62, 8007.08]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_02_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[0, -2927.43, 7934.49]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_03_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -1929.14, 8474.51]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_04_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -1556.55, -8692.53]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_02_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[-1.55, -1828.53, -2709.44]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_03_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -902.41, -7429.6]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_02_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -2051.27, -7198.26]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.glass_03_glass_0_glass_0_1.geometry}
                    material={materials.glass}
                  />
                </group>
                <group
                  position={[0, -2048.92, -7152.35]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.chrome_02_chrome_0_chrome_0_1.geometry}
                    material={materials.chrome}
                  />
                </group>
                <group
                  position={[0, -2117.74, -6896.92]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.glass_02_glass_0_glass_0_1.geometry}
                    material={materials.glass}
                  />
                </group>
                <group
                  position={[0, -2021.88, -6876.48]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.glass_01_glass_0_glass_0_1.geometry}
                    material={materials.glass}
                  />
                </group>
                <group
                  position={[0, -2050.88, -6926.13]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_01_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[0, -2117.74, -6789.4]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.chrome_01_chrome_0_chrome_0_1.geometry}
                    material={materials.chrome}
                  />
                </group>
                <group
                  position={[0, -2042, -7159.18]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.lights_01_lights_0_lights_0_1.geometry}
                    material={materials.lights}
                  />
                </group>
                <group
                  position={[0, -3514.7, 1732.61]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_02_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[-2427.26, -3502.16, 1679.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_01_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-2420.06, -3499.05, 1679.21]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_01_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -3456.95, 270.45]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_01_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[0, -2025.02, 241.32]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_02_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[0, -1638.82, 12.82]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_01_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[0, -702.1, -57.27]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_01_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -3843.48, 3934.54]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_15_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -3963.09, 3750.86]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_04_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[0, -2008.81, 2309.17]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_07_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[-3301.83, -1342.94, 5339.93]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_07_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[3265.51, -1285.1, -4479.22]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_14_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3498.55, -1281.66, -4459.29]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_07_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3498.76, -1268.74, -4459.29]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_06_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[-3262.9, -1285.1, -4426.06]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_13_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[3158.65, -1285.1, -5021.77]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_12_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -2721.97, -4759.94]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_11_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -2746.75, -4504.16]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_10_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3265.51, -1285.1, -4479.22]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_09_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[3276.92, -1285.1, -4424.85]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_06_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[-1284.51, -2875.91, -3783.63]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_08_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[3262.9, -1285.1, -4426.06]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_07_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3276.92, -1285.1, -4424.85]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_05_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[-3523.36, -1304.33, -5053.58]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_04_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[3656.44, -2191.4, -5053.23]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_27_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3158.65, -1285.1, -5021.77]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_22_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3196.6, -1338.85, 5959.79]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_21_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3353.68, -1342.94, 5972.27]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_13_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[-3288.5, -1342.94, 5972.27]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.brakes3_01_brakes3_0_brakes3_0_1.geometry}
                    material={materials.brakes3}
                  />
                </group>
                <group
                  position={[3505.11, -1345.31, 5370.42]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_03_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3288.97, -1342.94, 5341.09]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_04_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3288.97, -1342.94, 5341.09]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_05_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[3654.55, -1340.5, 5974.16]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_05_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3652.64, -1340.5, 5974.16]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_03_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[3582.82, -1360.72, 5974.08]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_02_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[-3722.73, -2293.32, 5973.72]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_06_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[3224.97, -1340.5, 5974.16]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_04_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -1787.84, -5994.87]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_05_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[-3296.54, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_12_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -1840.19, -1165.63]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_04_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[0, -2330.26, 67.87]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.interior_02_interior_0_interior_0_1.geometry
                    }
                    material={materials.interior}
                  />
                </group>
                <group
                  position={[3296.54, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_11_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -2040.89, 4786.87]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_03_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[-3291.37, -1342.94, 5392.22]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_20_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[3301.83, -1342.94, 5339.93]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_09_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[-3505.04, -1349.1, 5370.42]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_19_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3291.37, -1342.94, 5392.22]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_16_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -3414.23, -538.02]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.d_glass_01_d_glass_0_d_glass_0_1.geometry}
                    material={materials.d_glass}
                  />
                </group>
                <group
                  position={[2468.27, -3414.23, -538.02]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_05_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[2692.41, -2954.57, -599.76]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_26_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -3395.91, -1910.61]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.chrome_04_chrome_0_chrome_0_1.geometry}
                    material={materials.chrome}
                  />
                </group>
                <group
                  position={[0, -2510.7, -1238.37]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.interior_03_interior_0_interior_0_1.geometry
                    }
                    material={materials.interior}
                  />
                </group>
                <group
                  position={[2687.52, -2964.84, -2420.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_15_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[0, -3190.85, -2395.09]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_08_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -1722.78, 8826.1]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.plate_01_plate_0_plate_0_1.geometry}
                    material={materials.plate}
                  />
                </group>
                <group
                  position={[0, -2055.33, 8960.23]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_08_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[0, -2528.87, 8639.61]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_19_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -2521.65, 8643.67]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_18_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3.57, -1860.66, -1068.48]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.interior_01_interior_0_interior_0_1.geometry
                    }
                    material={materials.interior}
                  />
                </group>
                <group
                  position={[-3224.97, -1340.5, 5974.17]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_10_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -2890, 8290.37]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.red_01_red_0_red_0_1.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  position={[3288.5, -1342.94, 5972.27]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.brakes3_03_brakes3_0_brakes3_0_1.geometry}
                    material={materials.brakes3}
                  />
                </group>
                <group
                  position={[3390.56, -1342.94, 5972.27]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_09_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3196.6, -1338.85, 5972.89]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_17_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[3252.48, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.brakes3_02_brakes3_0_brakes3_0_1.geometry}
                    material={materials.brakes3}
                  />
                </group>
                <group
                  position={[-3252.48, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.brakes3_04_brakes3_0_brakes3_0_1.geometry}
                    material={materials.brakes3}
                  />
                </group>
                <group
                  position={[3591.59, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_18_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[-3319.05, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_17_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3589.76, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_12_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[3297.16, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.tire_mat5_04_tire_mat5_0_tire_mat5_0_1.geometry
                    }
                    material={materials.tire_mat5}
                  />
                </group>
                <group
                  position={[-3589.76, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_11_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[-3656.44, -2191.4, -5054.08]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_24_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[-3591.59, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_16_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[3523.36, -1304.33, -5053.73]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_shiny_10_black_shiny_0_black_shiny_0_1
                        .geometry
                    }
                    material={materials.black_shiny}
                  />
                </group>
                <group
                  position={[0, -2117.74, -6534.81]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_15_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -2213.61, -6574.98]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.glass_04_glass_0_glass_0_1.geometry}
                    material={materials.glass}
                  />
                </group>
                <group
                  position={[0, -1244.29, -6685.98]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.body_06_body_0_body_0_1.geometry}
                    material={materials.body}
                  />
                </group>
                <group
                  position={[0, -2117.74, -6774.27]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.chrome_03_chrome_0_chrome_0_1.geometry}
                    material={materials.chrome}
                  />
                </group>
                <group
                  position={[-3297.16, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.tire_mat5_03_tire_mat5_0_tire_mat5_0_1.geometry
                    }
                    material={materials.tire_mat5}
                  />
                </group>
                <group
                  position={[3319.05, -1285.1, -5053.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_14_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -1417.05, 8248.33]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_06_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[0, -2394.94, -3476.47]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.black_matt_23_black_matt_0_black_matt_0_1.geometry
                    }
                    material={materials.black_matt}
                  />
                </group>
                <group
                  position={[0, -2877.83, 8396.43]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.r_lights_01_r_lights_0_r_lights_0_1.geometry
                    }
                    material={materials.r_lights}
                  />
                </group>
                <group
                  position={[0, -874.99, 8355.12]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_09_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -2889.99, 8341.01]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.r_glass_01_r_glass_0_r_glass_0_1.geometry}
                    material={materials.r_glass}
                  />
                </group>
                <group
                  position={[0, -2873.36, 8308]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.carbon_10_carbon_0_carbon_0_1.geometry}
                    material={materials.carbon}
                  />
                </group>
                <group
                  position={[0, -3452.64, -3018.72]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.black_09_black_0_black_0_1.geometry}
                    material={materials.black}
                  />
                </group>
                <group
                  position={[0, -3451.5, -3020.49]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.d_glass_02_d_glass_0_d_glass_0_1.geometry}
                    material={materials.d_glass}
                  />
                </group>
                <group
                  position={[0, -2822.97, 8346.04]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.chrome_05_chrome_0_chrome_0_1.geometry}
                    material={materials.chrome}
                  />
                </group>
                <group
                  position={[0, -2826.54, 8376.12]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.glass_06_glass_0_glass_0_1.geometry}
                    material={materials.glass}
                  />
                </group>
                <group
                  position={[-1733.16, -2395.92, 8638.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_21_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
                <group
                  position={[0, -2822.97, 8374.49]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.glass_05_glass_0_glass_0_1.geometry}
                    material={materials.glass}
                  />
                </group>
                <group
                  position={[-2123.73, -2418.27, 8544.25]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.red_02_red_0_red_0_1.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  position={[1857.64, -2385.73, 8599.6]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={39.37}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.silver_20_silver_0_silver_0_1.geometry}
                    material={materials.silver}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Hennesey Venom F5.glb");

